### ISSUE TITLE
Isort fails in CI

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#132] opened 2020-05-21 00:26 UTC
* After running `isort -rc .`,  `isort -rc src/NZGBplugin/ --check --diff` passes locally

* When pushing changes as a result of  `isort -rc .` , `isort -rc src/NZGBplugin/ --check --diff` fails in CI

???? Very strange behavior. 
* Diffing local and remote show the files are the same.
* `isort --verison` shows "VERSION 4.3.21" both locally and in CI

!?

**Comment by SPlanzer** [comment] 2020-05-21 00:29
looks like iSort has many envi issues 
- https://github.com/timothycrosley/isort/issues/1147

**Comment by strk** [comment] 2020-05-21 04:10
Duplicate of #57 ?

**Closed** 2020-10-20 20:40 UTC
Labels: bug
