### ISSUE TITLE
Cannot add any external geometry of any type to a name

### ISSUE THREAD

**Issue by CMKMS-LINZ** [linz/gazetteer#219] opened 2020-09-10 05:14 UTC
### Bug Description

No external point, line, polygon layers can be added to a name with the add tool (ie UAT plan 3 step 54 onwards).

#### Steps to Reproduce

1. Open a name
2. Add a point layer, eg Survey Plan reference points
3. Highight some points, click Add Selected geometries to feature
4. Dialogue box asks to confirm, click OK
5. Nothing happens
6. Repeat with lines (nothing happens)
7. Repeat with polygons (nothing happens).

At step 4, the dialogue box is missing the word points/lines/polygons and failing to enumerate the geometry, which may provide some indication of what the problem is.

This has also been tested against layers created in EPSG 4167 to see if it had changed to only accept geometry in the same projection as the database, but nothing happens here either.

#### Desktop
 - Environment: [Windows 10]
 - Relevant Software Versions: [Gazetteer Plugin 2.0.1 UAT, QGIS 3.14.0]

#### Screenshots

**production**

![image](https://user-images.githubusercontent.com/61957082/92684204-0cdb7700-f389-11ea-86db-464e119a0271.png)

**UAT** 

![image](https://user-images.githubusercontent.com/61957082/92684156-e9b0c780-f388-11ea-8933-ebaa01fb1c06.png)

**Comment by SPlanzer** [comment] 2020-09-29 02:48
## Bug triage for QGIS3 initial release
I have been unable to reproduce this. I wonder if this is related to particular datasets being imported.  

* As per the image below I created a data set of ten points and associated these to Opotiki.
This also said "10 points".

* I also imported ~2000 address points and associated ~560 to a feature successfully. 

* I can confirm I had the same behaviour with lines and polygons

![image](https://user-images.githubusercontent.com/10425696/94505990-dd71a900-0268-11eb-9fab-ea72abe6067c.png)

### Next steps
Will need @CMKMS-LINZ to walk me through this

**Comment by CMKMS-LINZ** [comment] 2020-09-29 03:00
I did some further tests and immediately found that the issue occurs for **Multipolygons, Multilinestrings, Multipoints.**

It recognises and enumerates point, linestring, and polygon layers.

I saved a multilinestring as a shapefile and then checked in QGIS 2.6.1 / Prod 1.8.2 plugin, and you can add it, but I don't know if perhaps it's just being read as a linestring.

**Comment by SPlanzer** [comment] 2020-10-21 21:53
This was resolved when #218 was addressed. 

This was therefore released as part of 2.0.2-UAT but was over looked to get tested.  It looks like #212 will force another UAT release and we will have this undergo UAT then

**Closed** 2020-10-23 01:15 UTC
Labels: awaiting-user-acceptance, bug, release-2.0.3
